openapi: '3.0.1'
info:
  title: 'tasks-api'
  version: 'v1.0'
paths:
  /:
    get:
      summary: List tasks
      description: Returns a list of tasks
      responses:
        200:
          description: 'OK'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        500:
          description: 'Internal Server Error'
          content: {}
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: 'arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${APILambda.Arn}/invocations'
        responses:
          default:
            statusCode: '200'
        passthroughBehavior: 'when_no_match'
        httpMethod: 'POST'
        contentHandling: 'CONVERT_TO_TEXT'
        type: 'aws_proxy'
components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
