name: build

on:
  push:
    branches:
      - main
      - 'dev.*'
  pull_request:
  merge_group:

jobs:
  build:
    name: Build on Node.js v${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # supported node versions
        node: [18]
        os: ['ubuntu-latest']
        include:
          # additional test for current node version on windows
          - node: 18
            os: windows-latest
    steps:
      - run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - run: npm i -g npm
      - run: |
          echo "node: $(node --version)"
          echo "npm: $(npm --version)"
      - run: npm ci
      - run: npm run depcheck && npm run depcheck --workspaces
      - run: npm run lint:ci
      - run: npm run format:ci
      - run: npm run build --workspaces
      - run: npm run test --workspaces
      - run: echo ${{ github.ref }}
      - if: ${{ github.ref == 'refs/heads/main' }}
        env:
          CDK_DEPLOY_ACCOUNT: 887277492962
        run: npm run synth --workspaces
      - if: ${{ github.ref == 'refs/heads/staging' }}
        env:
          CDK_DEPLOY_ACCOUNT: 887277492962
        run: npm run synth --workspaces
